services:
  db:
    image: postgres:alpine
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
#    command: postgres -c tcp_keepalives_idle=60 -c tcp_keepalives_interval=10
    volumes:
      - db_data:/var/lib/postgresql/data/


  api:
    container_name: 'dag_api'
    build: .
    command: bash -c "uvicorn main:app --host=0.0.0.0 --port=8080 --reload"
    ports:
      - '8080:8080'
    depends_on:
      - db

    volumes:
      - dage-data:/app

volumes:
  dage-data:
  db_data:
