services:
  database:
    image: postgres:alpine
    restart: on-failure

    healthcheck:
      test: [ 'CMD', 'pg_isready -U postgres' ]
      interval: 30s
      timeout: 10s
      retries: 10

    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      POSTGRES_DB: "test_db"
      POSTGRES_PORT: 5432
      DB_USER: "postgres"

    volumes:
      - ./data:/var/lib/postgresql/data/

  api:
    container_name: "dag_api"
    build: .
    ports:
      - "8080:8080"
    environment:
        - "DATABASE_URL=postgresql://postgres@db:5432/test_db"
    depends_on:
      - database
      - redis


  redis:
    image: redis
    container_name: 'dag_api_redis'
    ports:
      - "6379:6379"
    volumes:
      - .data/db:/data
