"""update reading

Revision ID: 41fe6640e764
Revises: 7304efc2a05b
Create Date: 2025-10-23 12:19:53.814199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41fe6640e764'
down_revision: Union[str, None] = '7304efc2a05b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('readings', 'photo_urls',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False,
               comment='URLs des photos (minimum 2, maximum 5)',
               existing_comment='URLs des photos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('readings', 'photo_urls',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True,
               comment='URLs des photos',
               existing_comment='URLs des photos (minimum 2, maximum 5)')
    # ### end Alembic commands ###
