"""add meter_type

Revision ID: 7304efc2a05b
Revises: 9fafe982c0f4
Create Date: 2025-10-22 13:25:42.418108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7304efc2a05b'
down_revision: Union[str, None] = '9fafe982c0f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meters', sa.Column('meter_type', sa.String(length=100), nullable=False, comment='Type de compteur'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meters', 'meter_type')
    # ### end Alembic commands ###
