"""Initial migration

Revision ID: 9fafe982c0f4
Revises: 
Create Date: 2025-10-16 15:49:36.352813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9fafe982c0f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Nom de la ville'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identifiant unique UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Date de création'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Date de dernière modification'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cities_name'), 'cities', ['name'], unique=True)
    op.create_table('meters',
    sa.Column('code', sa.String(length=100), nullable=False, comment='Code unique du compteur'),
    sa.Column('owner_name', sa.String(length=255), nullable=False, comment='Nom du propriétaire'),
    sa.Column('address', sa.String(length=500), nullable=False, comment='Adresse du compteur'),
    sa.Column('meter_number', sa.String(length=255), nullable=False, comment='Numéro de série du compteur'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Statut actuel du compteur'),
    sa.Column('previous_reading', sa.Float(), nullable=True, comment='Dernière lecture enregistrée'),
    sa.Column('city_id', sa.UUID(), nullable=False, comment='Référence à la ville'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identifiant unique UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Date de création'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Date de dernière modification'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_meter_city_status', 'meters', ['city_id', 'status'], unique=False)
    op.create_index('idx_meter_code_city', 'meters', ['code', 'city_id'], unique=False)
    op.create_index(op.f('ix_meters_city_id'), 'meters', ['city_id'], unique=False)
    op.create_index(op.f('ix_meters_code'), 'meters', ['code'], unique=True)
    op.create_index(op.f('ix_meters_meter_number'), 'meters', ['meter_number'], unique=True)
    op.create_index(op.f('ix_meters_status'), 'meters', ['status'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=255), nullable=False, comment="Nom d'utilisateur unique"),
    sa.Column('full_name', sa.String(length=255), nullable=False, comment="Nom complet de l'utilisateur"),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Mot de passe hashé'),
    sa.Column('role', sa.String(length=50), nullable=False, comment="Rôle de l'utilisateur"),
    sa.Column('city_id', sa.UUID(), nullable=True, comment='Référence à la ville'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Statut actif/inactif'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identifiant unique UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Date de création'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Date de dernière modification'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_active_role', 'users', ['is_active', 'role'], unique=False)
    op.create_index('idx_user_role_city', 'users', ['role', 'city_id'], unique=False)
    op.create_index(op.f('ix_users_city_id'), 'users', ['city_id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('readings',
    sa.Column('meter_id', sa.UUID(), nullable=False, comment='Référence au compteur'),
    sa.Column('controller_id', sa.UUID(), nullable=True, comment='Référence au contrôleur'),
    sa.Column('reading_value', sa.Float(), nullable=False, comment='Valeur de la lecture'),
    sa.Column('reading_date', sa.DateTime(timezone=True), nullable=False, comment='Date et heure de la lecture'),
    sa.Column('comment', sa.String(length=1000), nullable=True, comment='Commentaire additionnel'),
    sa.Column('photo_urls', postgresql.ARRAY(sa.String()), nullable=True, comment='URLs des photos'),
    sa.Column('latitude', sa.Float(), nullable=True, comment='Latitude GPS'),
    sa.Column('longitude', sa.Float(), nullable=True, comment='Longitude GPS'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identifiant unique UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Date de création'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Date de dernière modification'),
    sa.ForeignKeyConstraint(['controller_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reading_controller_date', 'readings', ['controller_id', 'reading_date'], unique=False)
    op.create_index('idx_reading_date', 'readings', ['reading_date'], unique=False)
    op.create_index('idx_reading_meter_date', 'readings', ['meter_id', 'reading_date'], unique=False)
    op.create_index(op.f('ix_readings_controller_id'), 'readings', ['controller_id'], unique=False)
    op.create_index(op.f('ix_readings_meter_id'), 'readings', ['meter_id'], unique=False)
    op.create_index(op.f('ix_readings_reading_date'), 'readings', ['reading_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_readings_reading_date'), table_name='readings')
    op.drop_index(op.f('ix_readings_meter_id'), table_name='readings')
    op.drop_index(op.f('ix_readings_controller_id'), table_name='readings')
    op.drop_index('idx_reading_meter_date', table_name='readings')
    op.drop_index('idx_reading_date', table_name='readings')
    op.drop_index('idx_reading_controller_date', table_name='readings')
    op.drop_table('readings')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_city_id'), table_name='users')
    op.drop_index('idx_user_role_city', table_name='users')
    op.drop_index('idx_user_active_role', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_meters_status'), table_name='meters')
    op.drop_index(op.f('ix_meters_meter_number'), table_name='meters')
    op.drop_index(op.f('ix_meters_code'), table_name='meters')
    op.drop_index(op.f('ix_meters_city_id'), table_name='meters')
    op.drop_index('idx_meter_code_city', table_name='meters')
    op.drop_index('idx_meter_city_status', table_name='meters')
    op.drop_table('meters')
    op.drop_index(op.f('ix_cities_name'), table_name='cities')
    op.drop_table('cities')
    # ### end Alembic commands ###
